/*
GAME RULES:

- The game has 2 players, playing in rounds
- In each turn, a player rolls a dice as many times as he whishes. Each result get added to his ROUND score
- BUT, if the player rolls a 1, all his ROUND score gets lost. After that, it's the next player's turn
- The player can choose to 'Hold', which means that his ROUND score gets added to his GLBAL score. After that, it's the next player's turn
- The first player to reach 100 points on GLOBAL score wins the game

*/

var scores, rounds, activePlayer;

scores = [0,0];
round = 0;
activePlayer = 0;

// document.querySelector('#current-'+activePlayer).textContent = dice;
// document.querySelector('#current-'+activePlayer).innerHTML = '<em>'+dice+'</em>';

/*
if (activePlayer === 0) {
    activePlayer++;
} else {
    activePlayer--;
}
*/

var x = document.querySelector('#score-'+activePlayer).textContent;
console.log(x);


document.querySelector('.btn-new').addEventListener('click', function (){
    scores = [0,0];
    round = 0;
    document.getElementById('score-0').textContent = '0';
    document.getElementById('score-1').textContent = '0';
    document.getElementById('pocket-0').textContent = '0';
    document.getElementById('pocket-1').textContent = '0';
    document.querySelector('.dice').style.display = 'none';
    document.querySelector('.player-'+activePlayer+'-panel').classList.toggle('active');
    activePlayer = 0;
    document.querySelector('.player-'+activePlayer+'-panel').classList.toggle('active');
});

/* save for NEW GAME button

*/

// button click
document.querySelector('.btn-roll').addEventListener('click', function (){

    //random number is generated by 'dice'
    var dice = Math.floor(Math.random() * 6) + 1;

    // display result
    var diceDOM = document.querySelector('.dice');
    diceDOM.style.display = 'block';
    diceDOM.src = 'img/dice-'+dice+'.png';

    // update rounds score if roll > 1
    var scoreDOM = document.getElementById('pocket-'+activePlayer);
    if (dice > 1) {
        round+=dice;
        scoreDOM.textContent = round;
    } else {
        round = 0;
        scoreDOM.textContent = round;
        diceDOM.style.display = 'none';
        nextPlayer(); 
    }

});

document.querySelector('.btn-bank').addEventListener('click', function (){
    scores[activePlayer] += round;
    round = 0;

    // UI update
    document.getElementById('score-'+activePlayer).textContent = scores[activePlayer];
    document.getElementById('pocket-'+activePlayer).textContent = 0;
    document.querySelector('.dice').style.display = 'none';

    //Check for win condition
    if (scores[activePlayer] >= 100) {
        document.getElementById('name-'+activePlayer).textContent = 'WINNER!';
        document.getElementById('name-'+activePlayer).style.color = 'red';
        document.getElementById('score-'+activePlayer).style.color = 'red';
    } else {
        nextPlayer();
    }

});

function nextPlayer(){
    document.querySelector('.player-'+activePlayer+'-panel').classList.toggle('active');
    activePlayer === 0 ? activePlayer++ : activePlayer--;
    document.querySelector('.player-'+activePlayer+'-panel').classList.toggle('active');
};